title: Yieldstream
description: Yieldstream revolutionizes yield aggregation by implementing fully on-chain vault rebalancing.
theme: just-the-docs

url: https://0xyieldstream.github.io/docs

aux_links:
  Template Repository: https://github.com/0xyieldstream/docs
